import './App.css';
import 'fontsource-roboto';
import React, { useState, useEffect } from 'react';
import { DataGrid } from '@material-ui/data-grid';
import { makeStyles } from '@material-ui/core/styles';

const columns = [
    //{ field: 'id', headerName: 'ID', width: 25 },
    { field: 'classIcon', headerName: 'Class', flex: 1, 
        renderCell: (params) => 
        {return (<img alt='classIcon' className='classIcon' src={params.value}/>)} },
    { field: 'characterName', headerName: 'Name', width: 150 },
    { field: 'headImage', headerName: 'Head', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.row.headLevel}</div><img id='headImage' className='itemIcon' alt='headImage' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.row.headLevel}`},
    { field: 'neckImage', headerName: 'Neck', flex: 1,
        renderCell: (params) => 
            {return (<><div>{params.getValue('neckLevel')}</div><img id='neckImage' alt='neckImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('neckLevel')}`},
    { field: 'shoulderImage', headerName: 'Shoulder', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('shoulderLevel')}</div><img id='shoulderImage' alt='shoulderImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('shoulderLevel')}`},
    { field: 'chestImage', headerName: 'Chest', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('chestLevel')}</div><img id='chestImage' alt='chestImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('chestLevel')}`},
    { field: 'waistImage', headerName: 'Waist', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('waistLevel')}</div><img id='waistImage' alt='waistImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('waistLevel')}`},
    { field: 'legsImage', headerName: 'Legs', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('legsLevel')}</div><img id='legsImage' alt='legsImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('legsLevel')}`},
    { field: 'feetsImage', headerName: 'Feet', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('feetsLevel')}</div><img id='feetsImage' alt='feetsImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('feetsLevel')}`},
    { field: 'wristImage', headerName: 'Wrist', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('wristLevel')}</div><img id='wristImage' alt='wristImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('wristLevel')}`},
    { field: 'handsImage', headerName: 'Hands', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('handsLevel')}</div><img id='handsImage' alt='handsImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('handsLevel')}`},
    { field: 'finger1Image', headerName: 'Ring', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('finger1Level')}</div><img id='finger1Image' alt='finger1Image' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('finger1Level')}`},
    { field: 'finger2Image', headerName: 'Ring', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('finger2Level')}</div><img id='finger2Image' alt='finger2Image' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('finger2Level')}`},
    { field: 'trinket1Image', headerName: 'Trinket', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('trinket1Level')}</div><img id='trinket1Image' alt='trinket1Image' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('trinket1Level')}`},
    { field: 'trinket2Image', headerName: 'Trinket', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('trinket2Level')}</div><img id='trinket2Image' alt='trinket2Image' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('trinket2Level')}`},
    { field: 'backImage', headerName: 'Cloak', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('backLevel')}</div><img id='backImage' alt='backImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('backLevel')}`},
    { field: 'mainWeaponImage', headerName: 'Weapon', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('mainWeaponLevel')}</div><img id='mainWeaponImage' alt='mainWeaponImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('mainWeaponLevel')}`},
    { field: 'shieldImage', headerName: 'Shield', flex: 1, 
        renderCell: (params) => 
            {return (<><div>{params.getValue('shieldLevel')}</div><img id='shieldImage' alt='shieldImage' className='itemIcon' src={params.value}/></>)}, 
        valueGetter: (params) => 
            `${params.getValue('shieldLevel')}`},
];

/*const rows = [
    {id:"0", characterName:"Thelvadam", headLevel:"213", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03c.jpg", shoulderLevel:"197", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_cloth_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_robe_cloth_oribosdungeon_c_01.jpg", waistLevel:"226", legsLevel:"220", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_belt.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_pants_.jpg", feetsLevel:"226", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_bracer.jpg", handsLevel:"216", finger1Level:"203", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_cloth_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_argus_ring02.jpg", finger2Level:"184", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_ardenweald_02_green.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/spell_holy_championsbond.jpg", trinket2Level:"220", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/ability_pvp_gladiatormedallion.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"220", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_staff_2h_oribosdungeon_c_01.jpg", shieldImage:"", race:"Tauren", class:"Priest", spec:"Shadow", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_priest.jpg"},
    {id:"1", characterName:"Brøx", headLevel:"210", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_neck_ardenweald_01_silver.jpg", shoulderLevel:"200", chestLevel:"235", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_plate_mawraid_d_01.jpg", waistLevel:"213", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_belt.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_pants.jpg", feetsLevel:"213", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_bracer.jpg", handsLevel:"213", finger1Level:"197", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_glove.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendrethraid_01_gold.jpg", finger2Level:"213", trinket1Level:"197", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendrethraid_02_copper.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/spell_mage_focusingcrystal.jpg", trinket2Level:"223", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_maldraxxus_02_green.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"213", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_axe_2h_maldraxxus_d_01.jpg", shieldImage:"", race:"Orc", class:"Death Knight", spec:"Unholy", classIcon:"https://render-us.worldofwarcraft.com/icons/56/spell_deathknight_classicon.jpg"},
    {id:"2", characterName:"Talvisota", headLevel:"220", neckLevel:"226", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03c.jpg", shoulderLevel:"223", chestLevel:"235", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_plate_mawraid_d_01.jpg", waistLevel:"226", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_buckle.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_pants.jpg", feetsLevel:"226", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_bracer.jpg", handsLevel:"220", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_glove.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_argus_ring02.jpg", finger2Level:"220", trinket1Level:"213", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_pinkgold.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/sha_spell_fire_bluehellfire_nightmare.jpg", trinket2Level:"220", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_token_argentdawn3.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_sword_2h_oribosdungeon_c_01.jpg", shieldImage:"", race:"Troll", class:"Death Knight", spec:"Unholy", classIcon:"https://render-us.worldofwarcraft.com/icons/56/spell_deathknight_classicon.jpg"},
    {id:"3", characterName:"Zymandias", headLevel:"216", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_drustmask_d_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03c.jpg", shoulderLevel:"213", chestLevel:"235", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_plate_mawraid_d_01.jpg", waistLevel:"197", legsLevel:"220", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_plate_bastion_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_pants.jpg", feetsLevel:"226", wristLevel:"226", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_bracer.jpg", handsLevel:"213", finger1Level:"213", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_glove.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_oribos_01_silver.jpg", finger2Level:"226", trinket1Level:"226", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendreth_01_brown.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_archaeology_70_tauren_moosebonefishhook.jpg", trinket2Level:"220", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_leather_raiddruid_o_01chest.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"220", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mace_2h_bastion_d_01.jpg", shieldImage:"", race:"Troll", class:"Death Knight", spec:"Blood", classIcon:"https://render-us.worldofwarcraft.com/icons/56/spell_deathknight_classicon.jpg"},
    {id:"4", characterName:"Beardeddog", headLevel:"220", neckLevel:"210", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_leather_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"226", chestLevel:"213", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_leather_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_leather_revendrethraid_d_01.jpg", waistLevel:"220", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_leather_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_leather_oribosdungeon_c_01.jpg", feetsLevel:"226", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_leather_oribosdungeon_c_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_leather_revendrethraid_d_01.jpg", handsLevel:"235", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_leather_mawraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_01_red.jpg", finger2Level:"210", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_ardenweald_02_green.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_leather_raiddruid_o_01chest.jpg", trinket2Level:"226", backLevel:"220", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_scales_stonyorange.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_cape.jpg", mainWeaponLevel:"226", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glaive_1h_oribosdungeon_c_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_1h_oribosdungeon_c_01.jpg", race:"Blood Elf", class:"Demon Hunter", spec:"Vengeance", classIcon:"https://render-us.worldofwarcraft.com/icons/56/achievement_boss_illidan.jpg"},
    {id:"5", characterName:"Ketharion", headLevel:"220", neckLevel:"220", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"220", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_chest.jpg", waistLevel:"220", legsLevel:"235", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_belt.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_plate_mawraid_d_01.jpg", feetsLevel:"226", wristLevel:"207", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_bracer.jpg", handsLevel:"220", finger1Level:"220", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_glove.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_pinkgold.jpg", finger2Level:"220", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_orange.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/ability_warrior_endlessrage.jpg", trinket2Level:"220", backLevel:"220", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/ability_pvp_gladiatormedallion.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_cape.jpg", mainWeaponLevel:"220", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_sword_1h_bastion_d_02.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shield_1h_bastion_d_01.jpg", race:"Blood Elf", class:"Paladin", spec:"Holy", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_paladin.jpg"},
    {id:"6", characterName:"Shinoboo", headLevel:"213", neckLevel:"220", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"235", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_mawraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_robe_cloth_oribosdungeon_c_01.jpg", waistLevel:"213", legsLevel:"213", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_belt.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_pants_.jpg", feetsLevel:"226", wristLevel:"226", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_cloth_oribosdungeon_c_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_cloth_oribosdungeon_c_01.jpg", handsLevel:"226", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_cloth_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_argus_ring02.jpg", finger2Level:"226", trinket1Level:"213", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_brown.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_token_argentdawn3.jpg", trinket2Level:"226", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_80_titan02a.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"223", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_staff_2h_oribosdungeon_c_01.jpg", shieldImage:"", race:"Blood Elf", class:"Priest", spec:"Discipline", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_priest.jpg"},
    {id:"7", characterName:"Nurfazzar", headLevel:"226", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_cloth_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_neck_ardenweald_01_silver.jpg", shoulderLevel:"226", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_cloth_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_chest_.jpg", waistLevel:"226", legsLevel:"235", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_belt.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_mawraid_d_01_pant.jpg", feetsLevel:"213", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_bracer.jpg", handsLevel:"200", finger1Level:"213", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_cloth_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendrethraid_02_copper.jpg", finger2Level:"194", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_01_silver.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_80_titan02a.jpg", trinket2Level:"226", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_pet_spectralporcupinered.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_staff_2h_oribosdungeon_c_01.jpg", shieldImage:"", race:"Nightborne", class:"Warlock", spec:"Affliction", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_warlock.jpg"},
    {id:"8", characterName:"Harprogue", headLevel:"223", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_leather_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"213", chestLevel:"213", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_leather_revendrethraid_d_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_leather_revendrethraid_d_01.jpg", waistLevel:"203", legsLevel:"213", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_leather_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_leather_revendrethraid_d_01.jpg", feetsLevel:"210", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_leather_oribosdungeon_c_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_leather_revendrethraid_d_01.jpg", handsLevel:"213", finger1Level:"213", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_leather_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_copper.jpg", finger2Level:"235", trinket1Level:"197", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_maxlvlring_red.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/ability_pvp_gladiatormedallion.jpg", trinket2Level:"197", backLevel:"220", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_token_argentdawn3.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_cape.jpg", mainWeaponLevel:"220", shieldLevel:"213", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_knife_1h_oribosdungeon_c_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_knife_1h_bastion_d_01.jpg", race:"Goblin", class:"Rogue", spec:"Subtlety", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_rogue.jpg"},
    {id:"9", characterName:"Grego", headLevel:"235", neckLevel:"226", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_mawraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"220", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_robe_cloth_oribosdungeon_c_01.jpg", waistLevel:"220", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_belt.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_cloth_oribosdungeon_c_01.jpg", feetsLevel:"213", wristLevel:"220", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_cloth_oribosdungeon_c_01.jpg", handsLevel:"220", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_cloth_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_green.jpg", finger2Level:"220", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_orange.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/spell_holy_championsbond.jpg", trinket2Level:"220", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_artifact_tome01.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_staff_2h_oribosdungeon_c_01.jpg", shieldImage:"", race:"Undead", class:"Priest", spec:"Holy", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_priest.jpg"},
    {id:"10", characterName:"Mariolemieux", headLevel:"213", neckLevel:"226", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03c.jpg", shoulderLevel:"213", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_chest.jpg", waistLevel:"226", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_buckle.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_pants.jpg", feetsLevel:"226", wristLevel:"226", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_boots.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_bracer.jpg", handsLevel:"223", finger1Level:"207", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_oribosdungeon_c_01_glove.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelry_ring_45.jpg", finger2Level:"235", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_maxlvlring_red.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_leather_raiddruid_o_01chest.jpg", trinket2Level:"210", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_80_titan02a.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_mail_oribosdungeon_c_01.jpg", mainWeaponLevel:"213", shieldLevel:"213", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_sword_2h_revendreth_d_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_sword_2h_revendreth_d_01.jpg", race:"Mag'har Orc", class:"Warrior", spec:"Fury", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_warrior.jpg"},
    {id:"11", characterName:"Mizukisama", headLevel:"235", neckLevel:"226", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mail_mawraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"213", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_mail_revendrethraid_d_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_mail_revendrethraid_d_01.jpg", waistLevel:"226", legsLevel:"213", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_mail_revendrethraid_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_mail_revendrethraid_d_01.jpg", feetsLevel:"213", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_mail_revendrethraid_d_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_mail_revendrethraid_d_01.jpg", handsLevel:"220", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_mail_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_01_red.jpg", finger2Level:"213", trinket1Level:"197", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_copper.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_token_argentdawn3.jpg", trinket2Level:"213", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/spell_holy_championsbond.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mace_1h_maldraxxus_d_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shield_1h_maldraxxus_d_01.jpg", race:"Vulpera", class:"Shaman", spec:"Restoration", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_shaman.jpg"},
    {id:"12", characterName:"Fumino", headLevel:"210", neckLevel:"197", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_mawraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"213", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_chest_.jpg", waistLevel:"197", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_cloth_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_cloth_oribosdungeon_c_01.jpg", feetsLevel:"213", wristLevel:"216", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_cloth_oribosdungeon_c_01.jpg", handsLevel:"207", finger1Level:"197", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_cloth_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_01_dark.jpg", finger2Level:"197", trinket1Level:"197", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_01_pinkgold.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_token_argentdawn3.jpg", trinket2Level:"197", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/spell_holy_championsbond.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"213", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_staff_2h_ardenweald_d_02.jpg", shieldImage:"", race:"Nightborne", class:"Mage", spec:"Fire", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_mage.jpg"},
    {id:"13", characterName:"Ilidanshlong", headLevel:"226", neckLevel:"200", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_mail_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_neck_ardenweald_01_silver.jpg", shoulderLevel:"235", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mail_mawraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_mail_oribosdungeon_c_01.jpg", waistLevel:"226", legsLevel:"213", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_mail_revendrethraid_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_mail_revendrethraid_d_01.jpg", feetsLevel:"213", wristLevel:"226", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_mail_revendrethraid_d_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_mail_oribosdungeon_c_01.jpg", handsLevel:"220", finger1Level:"220", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_mail_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_pinkgold.jpg", finger2Level:"226", trinket1Level:"226", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendreth_01_brown.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_80_titan02a.jpg", trinket2Level:"226", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_alchemy_70_potion2.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"220", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bow_1h_ardenweald_d_01_temp.jpg", shieldImage:"", race:"Blood Elf", class:"Hunter", spec:"Marksmanship", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_hunter.jpg"},
    {id:"14", characterName:"Mooanna", headLevel:"213", neckLevel:"220", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_mail_revendrethraid_d_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"220", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_mail_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_mail_oribosdungeon_c_01.jpg", waistLevel:"213", legsLevel:"235", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_mail_revendrethraid_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mail_mawraid_d_01_pants.jpg", feetsLevel:"213", wristLevel:"207", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_mail_oribosdungeon_c_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_mail_oribosdungeon_c_01.jpg", handsLevel:"220", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_mail_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_70_raid_ring5b.jpg", finger2Level:"213", trinket1Level:"200", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_oribos_01_silver.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_icon_feather06a.jpg", trinket2Level:"194", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_livingruby_01.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_knife_1h_oribosdungeon_c_02.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shield_1h_ardenweald_d_01.jpg", race:"Tauren", class:"Shaman", spec:"Restoration", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_shaman.jpg"},
    {id:"15", characterName:"Asta", headLevel:"226", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_leather_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_neck_ardenweald_01_silver.jpg", shoulderLevel:"220", chestLevel:"213", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_leather_revendrethraid_d_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_leather_revendrethraid_d_01.jpg", waistLevel:"213", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_leather_revendrethraid_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_leather_revendrethraid_d_01.jpg", feetsLevel:"235", wristLevel:"200", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_leather_mawraid_d_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_leather_revendrethraid_d_01.jpg", handsLevel:"213", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_leather_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_brown.jpg", finger2Level:"226", trinket1Level:"226", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelry_ring_45.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_pet_spectralporcupinered.jpg", trinket2Level:"226", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/spell_animabastion_orb.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"226", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mace_1h_ardenweald_d_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_offhand_1h_oribosdungeon_c_01.jpg", race:"Tauren", class:"Druid", spec:"Balance", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_druid.jpg"},
    {id:"16", characterName:"Eunwol", headLevel:"216", neckLevel:"213", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_leather_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_neck_ardenweald_01_silver.jpg", shoulderLevel:"235", chestLevel:"203", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_leather_mawraid_d_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_leather_oribosdungeon_c_01.jpg", waistLevel:"216", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_leather_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_leather_oribosdungeon_c_01.jpg", feetsLevel:"223", wristLevel:"226", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_leather_oribosdungeon_c_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_leather_oribosdungeon_c_01.jpg", handsLevel:"213", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_leather_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_70_raid_ring5b.jpg", finger2Level:"226", trinket1Level:"213", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_brown.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_icon_wingbroken08d.jpg", trinket2Level:"200", backLevel:"226", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_maldraxxus_02_green.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_mail_oribosdungeon_c_01.jpg", mainWeaponLevel:"207", shieldLevel:"207", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_1h_oribosdungeon_c_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_knife_1h_oribosdungeon_c_01.jpg", race:"Zandalari Troll", class:"Rogue", spec:"Outlaw", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_rogue.jpg"},
    {id:"17", characterName:"Magnale", headLevel:"235", neckLevel:"220", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_leather_mawraid_d_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"220", chestLevel:"223", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_leather_revendrethraid_d_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_leather_oribosdungeon_c_01.jpg", waistLevel:"213", legsLevel:"220", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_leather_revendrethraid_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_leather_revendrethraid_d_01.jpg", feetsLevel:"213", wristLevel:"220", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_leather_revendrethraid_d_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_leather_revendrethraid_d_01.jpg", handsLevel:"220", finger1Level:"220", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_leather_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_pinkgold.jpg", finger2Level:"220", trinket1Level:"213", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_copper.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_scroll_16.jpg", trinket2Level:"200", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_alchemy_elixir_03.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"220", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_hand_1h_ardenweald_d_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_hand_1h_ardenweald_d_01.jpg", race:"Mag'har Orc", class:"Monk", spec:"Windwalker", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_monk.jpg"},
    {id:"18", characterName:"Shelfonaelf", headLevel:"235", neckLevel:"203", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_mawraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"203", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_cloth_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_chest_.jpg", waistLevel:"226", legsLevel:"223", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_cloth_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_cloth_oribosdungeon_c_01.jpg", feetsLevel:"213", wristLevel:"203", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_boot.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_cloth_oribosdungeon_c_01.jpg", handsLevel:"226", finger1Level:"210", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_cloth_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelry_ring_45.jpg", finger2Level:"213", trinket1Level:"213", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendrethraid_02_copper.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/70_inscription_vantus_rune_azure.jpg", trinket2Level:"213", backLevel:"220", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_maldraxxus_02_yellow.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_cape.jpg", mainWeaponLevel:"226", shieldLevel:"213", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_1h_oribosdungeon_c_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_offhand_1h_ardenweald_d_01.jpg", race:"Blood Elf", class:"Mage", spec:"Fire", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_mage.jpg"},
    {id:"19", characterName:"Mahjarrat", headLevel:"226", neckLevel:"225", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_helm.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_maxlvlneck_red.jpg", shoulderLevel:"220", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_shoulder.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_chest_.jpg", waistLevel:"210", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_cloth_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_cloth_oribosdungeon_c_01.jpg", feetsLevel:"197", wristLevel:"226", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_cloth_oribosdungeon_c_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_cloth_oribosdungeon_c_01.jpg", handsLevel:"220", finger1Level:"220", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cloth_revendrethraid_d_01_glove.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_orange.jpg", finger2Level:"220", trinket1Level:"197", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_bastion_02_copper.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/ability_pvp_gladiatormedallion.jpg", trinket2Level:"226", backLevel:"213", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/spell_holy_championsbond.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_cape_leather_revendrethraid_d_01.jpg", mainWeaponLevel:"226", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_1h_oribosdungeon_c_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_offhand_1h_oribosdungeon_c_01.jpg", race:"Troll", class:"Mage", spec:"Fire", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_mage.jpg"},
    {id:"20", characterName:"Fursoc", headLevel:"226", neckLevel:"226", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_leather_oribosdungeon_c_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03a.jpg", shoulderLevel:"223", chestLevel:"220", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_leather_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_leather_oribosdungeon_c_01.jpg", waistLevel:"213", legsLevel:"226", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_leather_revendrethraid_d_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_leather_revendrethraid_d_01.jpg", feetsLevel:"235", wristLevel:"213", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_leather_mawraid_d_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_bracer_leather_revendrethraid_d_01.jpg", handsLevel:"213", finger1Level:"226", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_leather_revendrethraid_d_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_argus_ring02.jpg", finger2Level:"207", trinket1Level:"226", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_revendrethraid_01_gold.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_alchemy_elixir_03.jpg", trinket2Level:"207", backLevel:"220", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_trinket_80_titan02a.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_cape.jpg", mainWeaponLevel:"226", shieldLevel:"220", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mace_1h_ardenweald_d_01.jpg", shieldImage:"https://render-us.worldofwarcraft.com/icons/56/inv_offhand_1h_ardenweald_d_01.jpg", race:"Zandalari Troll", class:"Druid", spec:"Balance", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_druid.jpg"},
    {id:"21", characterName:"Moumoku", headLevel:"226", neckLevel:"226", headImage:"https://render-us.worldofwarcraft.com/icons/56/inv_helm_drustmask_d_01.jpg", neckImage:"https://render-us.worldofwarcraft.com/icons/56/inv_7_0raid_necklace_03c.jpg", shoulderLevel:"207", chestLevel:"226", shoulderImage:"https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_mail_oribosdungeon_c_01.jpg", chestImage:"https://render-us.worldofwarcraft.com/icons/56/inv_chest_mail_revendrethraid_d_01.jpg", waistLevel:"216", legsLevel:"223", waistImage:"https://render-us.worldofwarcraft.com/icons/56/inv_belt_mail_oribosdungeon_c_01.jpg", legsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_pant_mail_oribosdungeon_c_01.jpg", feetsLevel:"213", wristLevel:"235", feetsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_boot_mail_revendrethraid_d_01.jpg", wristImage:"https://render-us.worldofwarcraft.com/icons/56/inv_mail_mawraid_d_01_bracer.jpg", handsLevel:"223", finger1Level:"210", handsImage:"https://render-us.worldofwarcraft.com/icons/56/inv_glove_mail_oribosdungeon_c_01.jpg", finger1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_02_brown.jpg", finger2Level:"210", trinket1Level:"220", finger2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_ring_maldraxxus_01_violet.jpg", trinket1Image:"https://render-us.worldofwarcraft.com/icons/56/inv_misc_trinket6oih_orb1.jpg", trinket2Level:"226", backLevel:"220", trinket2Image:"https://render-us.worldofwarcraft.com/icons/56/inv_alchemy_elixir_03.jpg", backImage:"https://render-us.worldofwarcraft.com/icons/56/inv_plate_revendrethraid_d_01_cape.jpg", mainWeaponLevel:"226", shieldLevel:"", mainWeaponImage:"https://render-us.worldofwarcraft.com/icons/56/inv_firearm_2h_revendrethquest_b_01.jpg", shieldImage:"", race:"Vulpera", class:"Hunter", spec:"Marksmanship", classIcon:"https://render-us.worldofwarcraft.com/icons/56/classicon_hunter.jpg"},
];*/

const useStyles = makeStyles(() => ({
    root: {
        //color: 'white',
        '& .MuiDataGrid-root': {
        },
        '& .MuiDataGrid-cell': {
            //flexDirection: 'column',
            //lineHeight: 'normal'
            //textAlign: 'center'
        },
        '& p': {
            //lineHeight: 'normal',
            //margin
        }
    },
  }));

function App() {
    const [error, setError] = useState(null);
    const [isLoaded, setIsLoaded] = useState(false);
    const [rows, setRows] = useState([]);

    useEffect(() => {
        fetch("http://vailveix.com/wow.php", {crossDomain: true})
          .then(res => res.json())
          .then(
            (response) => {
                setIsLoaded(true);
                setRows(response);
            },
            (error) => {
                setIsLoaded(true);
                setError(error);
            }
          )
      }, [])

    const classes = useStyles();

    if(error){
        return <div>Error: {error.message}</div>;
    }
    else if(!isLoaded){
        return <div>Loading...</div>;
    }
    else{
        return (
            <div className="App">
                <header className="App-header">
                    <p>P A N I C Raid Gear</p>
                </header>
                <DataGrid className={classes.root} rows={rows} columns={columns}  autoHeight rowHeight="50" />
            </div>
        );
    }
}

export default App;
